files: |
  (?x)^(
    server/.*\.py |
    alembic/ |
    app.py
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.245'
    hooks:
      - id: ruff
        args: ['--fix', '--line-length', '100000'] # line length is forced by black
        types: [python]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--atomic', '--profile', 'black', '--line-length', '110']

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=110]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
      - id: mypy
        args: [ --config-file, .mypy.ini ]
        types: [ python ]
        additional_dependencies: [
          types-python-dateutil,
          types-PyMySQL,
          types-pytz,
          types-requests,
          types-retry,
          types-six
        ]
        exclude: |
          (?x)^(
            tests/ 
          )
exclude: |
  (?x)^(
    .venv/ |
    venv/
  )